// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mclllaebhfdjczeumgdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbGxsYWViaGZkamN6ZXVtZ2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTU3NTMsImV4cCI6MjA2NjYzMTc1M30.hwNU63hw7E2yxxM5HFNb4JVfkSi3kZWo1Zm5txZNftw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);